#!/bin/bash
# Builds NGINX.
# This script is designed to run in a Heroku Stack Docker
# image. More information on the Heroku Stack can be found
# at https://devcenter.heroku.com/articles/stack

set -e

NGINX_VERSION=${NGINX_VERSION-1.25.2}


nginx_tarball_url=https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz

rm -rf /tmp/nginx*

temp_dir=$(mktemp -d /tmp/nginx-download.XXXXXXXXXX)

cd $temp_dir
echo "Temp dir: $temp_dir"

echo "Downloading $nginx_tarball_url"
curl -L $nginx_tarball_url | tar xzv


# build `nginx`
(
  cd nginx-${NGINX_VERSION}
  ./configure \
    --with-http_auth_request_module \
    --with-http_ssl_module \
    --with-http_sub_module \
    --prefix=/tmp/nginx
  make install
)


# build `nginx-debug`
(
  cd nginx-${NGINX_VERSION}
  ./configure \
    --with-debug \
    --with-http_auth_request_module \
    --with-http_ssl_module \
    --with-http_sub_module \
    --prefix=/tmp/nginx-debug
  make install
)

release_dir=$(mktemp -d /tmp/nginx-release.XXXXXXXXXX)

cp /tmp/nginx/sbin/nginx $release_dir/nginx
cp /tmp/nginx-debug/sbin/nginx $release_dir/nginx-debug
cp /tmp/nginx/conf/mime.types $release_dir/mime.types
tar -zcvf /tmp/nginx-"${STACK}".tgz -C $release_dir .
cp /tmp/nginx-"${STACK}".tgz $1
